### ISSUE TITLE
Keys modifier processing

### ISSUE THREAD

**Issue by sinev-valentine** [arrayio/array-io-keychain#10]
Parent task: https://github.com/arrayio/array-io-keychain/issues/7

Some keyboard layout have  key modifiers (French, for example).  This provides the ability to press more one key for one symbol. It is necessary to  implement read this symbols on low-level.

The task is pending.

**Comment by vladiuz1** [comment]
Fix english: `Only English(American) keyboard layout supported.`

**Comment by sinev-valentine** [comment]
Now all English keyboard layouts  supported
