### ISSUE TITLE
security module API improvement

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#106]
Need to improve security module API because of increasing the number of interface functions and these parameters.

Jsonrp like interface through one single function is preferred. Need to create json protocol for exchanging of events/messages with the security module.

**Comment by roman-modelist-dev** [comment]
List of possible commands
- sign_hex
- sign_hash
- unlock
- unlock_for_remove
- password_for_export
- password_for_import
- create_key
- print_mnemonic

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 02/11/19 - 02/19/19
Work session total: 49:36:55

Grand total: 73:59:50
