### ISSUE TITLE
Bitcoin js: BTC transaction with multiple inputs

### ISSUE THREAD

**Issue by Avvrik** [arrayio/array-io-keychain#112]
Create an example of JavaScript integration code for a Bitcoin transaction with multiple inputs.  
Note that while a transaction might have multiple inputs, a user should insert the passphrase only once for better user experience. 

This should be similar to the Ethereum transaction example which can be found [here](https://github.com/arrayio/array-io-keychain/wiki/How-to-sign-Ethereum-transaction-via-KeyChain).

Use this library: https://github.com/bitcoinjs/bitcoinjs-lib

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 02/21/19 - 02/27/19
Work session total: 30:44:28

Grand total: 30:44:28
