### ISSUE TITLE
add canceled result for input password operations

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#114]
Need to add canceled result for input password operations

1) [x] -- keychain common
2) [ ] -- windows sec module
3) [ ] -- linux sec module
4) [x] -- macos sec module

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 02/27/19 - 04/01/19
Work session total: 181:06:18

Grand total: 181:06:18
