### ISSUE TITLE
auto restore key_data and log folders in keychain directory

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#120]
Need to add auto restoring key_data and log folders in keychain directory if user will remove it after installation.

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 02/20/19 - 04/11/19
Work session total: 68:14:56

Grand total: 68:14:56
