### ISSUE TITLE
implement signing transaction for ethereum

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#17]
Need to implement signing transaction for ethereum.

Need to run bitcoin testnet -- is it possible to start ethereum node on local machine without connection to testnet?
Need to modify ethereum cli_wallet to generate unsigned binary transaction.

**Comment by vladiuz1** [comment]
Did you try this:

* https://gist.github.com/fishbullet/4c36ecd6d6932adae24c68c8750894e6

?

**Comment by vladiuz1** [comment]
@cyberkostyan do we wait for our *.nodes.array.io?

**Comment by cyberkostyan** [comment]
@vladiuz1 @roman-modelist-dev Yes, next week we will have working gate in our SMP network

**Comment by vladiuz1** [comment]
For now talk to @noxonsu team to help you with JS based test cases for both ethereum and bitcoin signing.

**Comment by roman-modelist-dev** [comment]
I tryed to copy sign function from ethereum to libfc (bitshares).
At this moment I am still fixing compile errors. I have a quiestion, is it necessary at all to link graphene libraries (libfc, graphene_utils, etc) to the keychain.
I suggest to stop trying to copy ethereum function to bitshares library. 

I assume it will be better to remove graphene libraries from keychain, use ethereum sign function over actual bitcoin version of secp256k1 library. Actually, we will create new library for keychain, that will contain minimal set of required functions.

When we will ensure than keychain can sign ethereum transactions we can use keychain library to sign array transaction. Also we can add to new library functions fot signing graphene transactions without using libfc, etc.

**Comment by roman-modelist-dev** [comment]
Need to add another blockchain type into sign command: ethereum.

**Comment by roman-modelist-dev** [comment]
can we close this issue?

**Comment by roman-modelist-dev** [comment]
via Hubstaff
User: Roman Ibragimov

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 07/11/18 - 11/27/18
Work session total: 56:53:52

Grand total: 56:53:52
