### ISSUE TITLE
change algo to cipher

### ISSUE THREAD

**Issue by vladiuz1** [arrayio/array-io-keychain#22]
All mentions of Algorithm that relate to symmetric encryption should be renamed to 'cipher'.

This shiould be done inside code, and .md files.

```json
{ "command": "create", "params": { "keyname": "test1", "encrypted": true, "algo": "CIPHER_AES256", "curve": "CURVE_SECP256K1" } }
```

should look like this:

```json
{ "command": "create", "params": { "keyname": "test1", "encrypted": true, "cipher": "aes256", "curve": "secp256k1" } }
```

also 

remove relics such as prefixes in the name of cipherss and curves, and make them lower case letters.

- [x] rename to cipher
- [x] remove CIPHER_ prefix
- [x] remove CURVE_ prefix
- [x] make names of curves and ciphers lowercase

**Comment by vladiuz1** [comment]
when done?

**Comment by sinev-valentine** [comment]
remove CIPHER_ prefix - done
 remove CURVE_ prefix - done
 make names of curves and ciphers lowercase - done

**Comment by roman-modelist-dev** [comment]
via Hubstaff
User: Roman Ibragimov

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 07/19/18 - 07/19/18
Work session total: 0:55:03

Grand total: 0:55:03
