### ISSUE TITLE
implement signing transaction for graphene blockchains without bitashares core libraries

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#28]
It is need to implement signing transaction for graphene blockchains without bitashares core libraries.

We don't want to link:
 - libfc.a
 - graphene_utitlities.a
 - libsecp256k1.a -- bitshares version of this library.

We need to use secp256k1 library from https://github.com/bitcoin-core/secp256k1.git, not from https://github.com/bitshares/secp256k1-zkp.git.

It is possible to add required function to bitcoin-core/secp256k1 if it is necessary to sign graphene transactions.

**Comment by sinev-valentine** [comment]
Private and public keys must be stored in hex.
Submodule array-io-core must be excluded. For this:
 - SHA2 must be imported to keychain.
 - For create private and puclic keys are needed replace bitshares to  ethereum functions.

**Comment by roman-modelist-dev** [comment]
* submodule array-io-core must be excluded
* functionality from fc::sha256 must be moved to keychain
* for working with crypto key may be used code from ethereum: 
  - ethereum/crypto/Common.h ethereum/crypto/Common.cpp
  - ethereum/core/sha3.h ethereum/crypto/Sha3.cpp
  - ethereum/core/FixedHash.h ethereum/core/FixedHash.cpp
* sign function must be implemented gracefully
* change private key store format from wif to hex. If private key is encrypted, then hex string is used as plain (unencrypted) data 
* secp256k1 must be used as git submodule

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 08/30/18 - 09/12/18
Work session total: 35:59:04

Grand total: 35:59:04
