### ISSUE TITLE
Test keychain ethereum sign format on ethereum node

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#33]
Need to test keychain ethereum sign format on ethereum node

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 10/30/18 - 11/01/18
Work session total: 9:35:32

Grand total: 9:35:32

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 11/01/18 - 11/02/18
Work session total: 0:12:08

Grand total: 9:47:40
