### ISSUE TITLE
keychain_pass_entry_app can not start password entry window on Win10

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#36]
Bug has been detected: keychain_pass_entry_app can not start password entry window on Win10.

keychain_pass_entry_app successfully run and show pass entry window on Win7, but does not work on Win10.

Need to fix it.

**Comment by NuclearRazor** [comment]
Is that already fixed? Works well on Windows 10 local machine.

**Comment by roman-modelist-dev** [comment]
via Hubstaff
User: Roman Ibragimov

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 10/26/18 - 10/26/18
Work session total: 4:29:16

Grand total: 31:07:17

**Comment by IluhaPuts** [comment]
via Hubstaff
User: Ilia Puts

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 10/30/18 - 11/20/18
Work session total: 26:38:01

Grand total: 31:07:17
