### ISSUE TITLE
Create installer for Windows 7/8/10

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#38]
Need to create installer for Windows 7/8/10. Installer for Win10 is priority target.

**Comment by NuclearRazor** [comment]
Here is some conclusions about WIX - method of installer creation:

**Embed vcredist with wix installation files:**

There no need to write separate Fragment module (in xml tree) with inherited vcredist elements (bootstrap - method), utils for searching installed libraries etc. There a lot of valid cases for only old version of WIX installer ( < 3 ), but we use 3.11 version and here is simplier method:

http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_vcredist.html

And about Redist list and it's extensions:

https://docs.microsoft.com/en-us/visualstudio/productinfo/2012-redistribution-vs

Bootstraping method:

https://gist.github.com/nathancorvussolis/6852ba282647aeb0c5c00e742e28eb48

(Was problem for detecting MSVCP140D.DLL, VCRUNTIME140D.DLL, UCRTBASED.DLL, dynamic libs by keychain binary)

- source msm - modules placed in MVS MergeModules folder 

**Notes about test cases (states of installation files and its dependecies):**

1 - update installed version (only files has already changed) by new installer
2 - update installed version without files updates but with vcredist update by new installer
3 - is cases 1, 2 connected with Product Version parameter

- if folder deleted by user, installer will not detect this deletion and advice to repair or delete files (normal behaviour causes by GUID data that already stored in OS registy and some other values, see:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WSKeychain)

- check flags get return values from embed files

**Comment by roman-modelist-dev** [comment]
done
next step add key manager into windows installer

**Comment by roman-modelist-dev** [comment]
via Hubstaff
User: Roman Ibragimov

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 11/12/18 - 01/11/19
Work session total: 1:15:03

Grand total: 1:15:03
