### ISSUE TITLE
create key manager GUI (all platforms)

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#44]
1) [ ] - MacOS
2) [ ] - Windows
3) [ ] - Linux

Need to create key manager GUI for all platforms
Prototype for gui is here
![11](https://user-images.githubusercontent.com/37844238/51052459-c2b85600-15e7-11e9-800f-f590c78ceb3d.jpg)

We'll have next fields on main table
- full keyname (min size = 18 symbols)
- description
- date: last usage date or creation date if not usage yet

Key info window:
1) full keyname
2) descryption
3) last usage date
4) public key
5) location
6) cipher type or non-encrypted flag
7) creation date
8) keychain version

Functions must be implemented:
1) show list of all keys
2) show key information
3) edit key description -- need successful unlock before delete
4) delete key -- need successful unlock before delete
5) export all keys -- need to ecrypt archive on mnemonic or user password
6) import all keys (with decryption key archive)
7) show keychain websocket service status
8) show logs and last error info
9) about function

**Comment by roman-modelist-dev** [comment]
@sinev-valentine suggested to use out of box solution - https://github.com/joewalnes/websocketd

This websocket server supports all required platforms (MacOS, Windows, Linux). This server can run keychain executable file every time as new websocket connection will be established. On Linux and MacOS we can use stdin and stdout streams in pipe mode. On Windows we can write simple wrapper exe file, that will open connection with named pipe and redirect there json command.

This solution is seems to be simple and can be quick integrated. But we need to figure out is it possible to use this websocket server bypassing same origin policy.

**Comment by IluhaPuts** [comment]
via Hubstaff
User: Ilia Puts

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 01/10/19 - 01/30/19
Work session total: 18:51:44

Grand total: 42:48:24
