### ISSUE TITLE
Websocker server (all platforms)

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#45]
1) [ ] - MacOS
2) [x] - Windows
3) [ ] - Linux

Need to create websocket server for all platforms. 

WS server will run as service (linux daemon). WS server will install into the OS by keychain package jointly with keychain app (keychain service on Windows)

How it work:
WS server
client app => receive rpc request by web socket transport - it may be requests from client apps =>
=> open pipe channel with keychain (keychain service on windows) => 
=> send keychain commands (json format) => 
=> receive keychain response => 
=> translate keychain response to the websocket => client app

**Comment by IluhaPuts** [comment]
keychain websocket service on win7, win10 is tested with secure credentials dialog
