### ISSUE TITLE
Implement lock/unlock behavior in keychain

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#46]
Need to implement lock/unlock behavior in keychain.

Keychain must store decrypted private key in memory during the specified time (unlock timeout). Store time is configured value. At this step this value may be hardcoded. Next unlock timeout value will be able to set by configuration. Storing decrypted private key in memory provide as sign next user transactions without necessary of entering key password every time.

Decrypted private key must store in keychain memory
- while pipe is open
- while timeout is not expired

Also it need to add lock command to keychain API.

lock command must have following parameters:
 - username - string param, providing key name to be locked

**Comment by sinev-valentine** [comment]
The Lock / Unlock  functions  is defined as exsperimental.  Therefore , user interface must to inform  user about this by imaging the red padlock. The command Unlock must be applied for specific keyname, not for all keys. 
Description  implementation changes:
- remove command "set_unlock_time";
- add optional parametr "unlock_time" to command "sign_hex", "sign_hash";  Default value - 0 seconds.
- add visualization "unlock mode" to gui.

**Comment by roman-modelist-dev** [comment]
Need to call new interface function get_trx_unlock in unlock command handler

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 11/14/18 - 12/11/18
Work session total: 70:57:04

Grand total: 70:57:04
