### ISSUE TITLE
Implement parse transaction mechanism in keychain

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#49]
Need to implement parse transaction mechanism in keychain.
Description wil come soon...

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 01/09/19 - 01/15/19
Work session total: 32:19:26

Grand total: 32:19:26
