### ISSUE TITLE
secure password entry

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#5]
Need to implement secure password entry.
Platforms must be supported:
1) [x] windows 7 and newer
2) [x] macos 10.11 and newer
3) [x] linux: ubuntu 16.04 and newer (list of distributions can be extended)

Platform should be supported in future:
1) android
2) ios

Design features

Windows
 - run keychain as service, 
 - using jsonrpc interface to permorm keychain operations,
 - keychain service call password window in secure mode.
The immediate task: Need to figure out how to implement password window call in secure mode.

Macos
The immediate task: Need to figure out design features for secure password entry on Macos.

Linux (X11)
 - using suid bit, to launch keychain app on behalf of the keychain user,
 - keychain app call password window in secure mode.
The immediate task: Need to figure out how to implement password window call in secure mode on X11 systems.

**Comment by roman-modelist-dev** [comment]
secure password entry has been implemented for windows platform

**Comment by sinev-valentine** [comment]
secure password entry has been implemented for Linux platform

**Comment by roman-modelist-dev** [comment]
I think, this task is done
