### ISSUE TITLE
Run keychain from WS server on Windows

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#50]
Need to run WS server https://github.com/joewalnes/websocketd/wiki/Ten-minute-tutorial on Windows. In this configuration we can run keychain on windows without keychain_service_win. 
Need to modify existing keychain command line app. This app will run by ws server in system user context and can run pass_ent_app utility.

Need to try run keychain in this configuration.

**Comment by roman-modelist-dev** [comment]
done

**Comment by IluhaPuts** [comment]
via Hubstaff
User: Ilia Puts

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 11/18/18 - 11/18/18
Work session total: 0:57:11

Grand total: 0:57:11
