### ISSUE TITLE
Run WS server on Linux

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#52]
Need to run ws server on Linux 
https://github.com/joewalnes/websocketd/wiki/Ten-minute-tutorial

Need to run keychain app by ws server.

**Comment by sinev-valentine** [comment]
Create wrapper for websocket-server start.

For start websocket-server the followed scheme is proposed:
- daemon is started with root privileges;
- daemon is find process Xorg and to save its pid and username under which Xorg was started;
- for this user X-server authentication is disabled by performing executing xhost;
- downgrade privileges to the keychain_service user by perform setuid command;
- forked child process under keychain_service user;
- under child process start winsocketd by performing exec();
- parent process  scanned table processes to to find pid of Xorg. If pid is changed, than X-server authentication is to disabled again;
- timeout for scannig - 10 seconds.

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 12/11/18 - 12/29/18
Work session total: 75:32:50

Grand total: 75:32:50
