### ISSUE TITLE
Implement ethereum parser for keychain

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#56]
Need to implement ethereum parser module for keychain. This module will be embedded into keychain and will be linked statically. Therefore we can use just C++ for quick result.

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 11/23/18 - 12/11/18
Work session total: 55:48:08

Grand total: 55:48:08
