### ISSUE TITLE
Implement custom pass entry window (Windows, Qt)

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#57]
Need to implement custom pass entry window using Qt (Windows). This windows will show user parsed transaction.
Next step is integration window and parse module => we will consider this later.

[design_sign_window.zip](https://github.com/arrayio/array-io-keychain/files/2605086/design_sign_window.zip)

**Comment by IluhaPuts** [comment]
via Hubstaff
User: Ilia Puts

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 11/26/18 - 12/21/18
Work session total: 49:42:59

Grand total: 49:42:59
