### ISSUE TITLE
Implementing basic functionality of keychain

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#6]
Need to implement basic functions of keychain declared in #2.

**Comment by roman-modelist-dev** [comment]
At this moment it is implemented:
- sign command for bitshares
- key files search by filename and username

Aslo reflection future from lib/fc has been applied for parsing/serialization pipe commands and parsing key files.

Next step:
- key encryption implementing

**Comment by roman-modelist-dev** [comment]
Today I was explored openssl api to find out how key encryption is implemented in the openssl.
Current status: in progress

**Comment by roman-modelist-dev** [comment]
Question:
Keychain can handle requests from different users in the OS. Сonsequently, one user can remove key owned by another user.
Is it necessary to provide access control system? If necessary we need to discuss how to properly implement.
I assume on linux we can use real UID to identify users. But it may not be possible on other platforms. Another way is to use user password for authenticate user request. However keychain use cases allow to store keys in unencrypted format.
So, it is needed to discuss this question on the focus group.

**Comment by roman-modelist-dev** [comment]
File encryption (symmetric) has been realized.

Next step: user identification
 - Creating abstract interface function that will identify user sending request. 
 - Implementing identify function on window and unix, that idenity user by operating system api.
 - Modify rpc functions and key file format if needed.

**Comment by roman-modelist-dev** [comment]
Implementing identify function, brief overview:
1) unix -- using SO_PEERCRED option 
 http://man7.org/linux/man-pages/man7/socket.7.html
 https://stackoverflow.com/questions/9898961/is-there-a-way-to-get-the-uid-of-the-other-end-of-a-unix-socket-connection
2) windows 
 - get list of ports and process pid - s
 - get user ID that own process (process owner)

**Comment by enaredzic** [comment]
Is this issue solved?
