### ISSUE TITLE
Move SecureModuleWrapper code to separated library

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#60]
Need to move SecureModuleWrapper and depends code to separated library.
keychain_root_dir
=> keychain_app -> depends: keychain_windows/secmod
=> keychain_windows/keychain_service_win -> depends: keychain_windows/secmod
вырезать из keychain_windows "SecureModuleWrapper"
 - SecureModuleWrapper.h
 - SecureModuleWrapper.cpp
 - NamedPipeServer.h
 - NamedPipeServer.cpp
 - ServiceLogger.h
 - ServiceLogger.cpp
=> keychain_windows/secmod
добавить в secmod класс "SecureModuleWrapper"
 + SecureModuleWrapper.h
 + SecureModuleWrapper.cpp
 + NamedPipeServer.h
 + NamedPipeServer.cpp
 + ServiceLogger.h
 + ServiceLogger.cpp

**Comment by NuclearRazor** [comment]
Is that static library already implemented?
