### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by dtaipov** [arrayio/array-io-keychain#63]
1) Unknown command:

request:
`{"command": "unknown123"}`

response:
> {"id":0,"error":"7 bad_cast_exception: Bad Cast\ninvalid name 'unknown123' in enum 'keychain_app::command_te'\n    {\"key\":\"unknown123\",\"enum\":\"keychain_app::command_te\"}\n    exception.cpp:226 throw_bad_enum_cast"}
> {"id":0,"error":"Bad Cast"}

The error name is "Bad Cast" which doesn't reflect the error type. Would me more clear if the error was called like "Unknown command".

2) If not valid json passed, the app crashes

request:
`sdfsdfsd`

response:

> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Parse error: common error while parsing command - unexpected symbols
> [1]    25152 abort (core dumped)  ./keychain.ubuntu

3) if empty json passed:

request:
`{}`

response:
`{"id":0,"error":"method is not implemented"}`

Proposed format of errors:
https://github.com/arrayio/array-io-keychain/wiki/WebSocket-API#errors

**Comment by roman-modelist-dev** [comment]
1) fixed 
{"command":"asdfsa"}
{"id":0,"error":{"code":2,"name":"rpc_command_parse_code","message":"Command cannot be parsed: invalid name 'asdfsa' in enum 'keychain_app::command_te' => cannot parse command","trace":[{"level":"error","file":"exception.cpp","line":239,"method":"throw_bad_enum_cast","timestamp":"2019-02-04T13:43:48"},{"level":"error","file":"keychain.cpp","line":85,"method":"operator()","timestamp":"2019-02-04T13:43:48"}]}}
2) Json objects are used as message separators. So, if keychain receive bytes outside of json object keychain does not know how interpret this bytes.
3) {} is equal {"command":0}. Null code is not implemented. What kind of error message would you prefer?
