### ISSUE TITLE
Use JSON-RPC protocol

### ISSUE THREAD

**Issue by dtaipov** [arrayio/array-io-keychain#69]
Now KeyChain protocol is quite similar to JSON-RPC.
https://www.jsonrpc.org/specification
Differences between current protocol and JSON-RPC 2.0:

| | Current KeyChain | JSON-RPC |
| ------------- | ------------- | ------------- |
| **id field type** | number  | string, number  |
| **method field name** | "command" | "method"  |
| **jsonrpc: "2.0" field** | not implemented | required  |
| **error field format** | string | Object {code, message, data}  |
| **batch requests support** | no | required  |

 Maybe it's better to use JSON-RPC specification itself since it's a standard?

**Comment by cypherpunk99** [comment]
https://www.npmjs.com/package/rpc-websockets

**Comment by cypherpunk99** [comment]
1. In case of use timeouts one single response - one single immediate answer tying our hands, so we can not get event when timer is exceed. GUI becomes unresponsive. Multiple answers in async way with JSON-RPC solve this problem
2. Protocol error codes reinvention and development costs time. JSON-RPC already have it
3. Ready to use libraries such as rpc-websockets also reduce dev time. 
4. Clear and beauty wrapper architecture in case of JSON-RPC usage. 
Based on rpc_id queue promise resolver/rejector object architecture https://github.com/elpheria/rpc-websockets/blob/86640d30f82748adabeabefa85cafe625a68f2f7/src/lib/client.js#L107 help us avoid CPU heavy while loop implementations https://github.com/arrayio/array-io-client/blob/develop/electron/main/helpers/systemComponents/Keychain/queue.ts#L40
