### ISSUE TITLE
Implement secure password entry on linux (X11 server)

### ISSUE THREAD

**Issue by roman-modelist-dev** [arrayio/array-io-keychain#7]

**Comment by roman-modelist-dev** [comment]
Some x11 manuals about this: https://www.x.org/archive/X11R7.5/doc/security/XACE-Spec.pdf

**Comment by sinev-valentine** [comment]
X11 protocol  have extention XTEST. It can intercepted  and synthesize events.
Keystrokes can also be intercepted by the application that caused the XGrabKeyboard.
It is necessary make call xGrabKeboards, so that no one else cause it.
Also, it is necessary look field send_event of structure  XAnyEvent  (or any other, that have larger size, such as XKeyEvent), to  avoid  the effects of synthesized events.
Another  way to solve problem safety  input password  -  start  a new instance of the xserver, ask for password, and then to do VT switch back. But it is  harder to implement, that this would be  looks nice  for the user.

**Comment by sinev-valentine** [comment]
Sample project "input PIN-code" fo X11:
https://github.com/msharov/pinentry-xlib

Discussion of problem:
https://www.linux.org.ru/forum/development/481313

A Brief intro to X11 Programming:
http://math.msu.su/~vvb/2course/Borisenko/CppProjects/GWindow/xintro.html
http://yenolam.com/writings/xlibbook-0.5.pdf

As can be seen from sample project and  discussion of the problem,  also it is necessary  cause xGrabServer().

**Comment by sinev-valentine** [comment]
XGrabServer()  is not blocking keyboard intercept.
Example of  secure input password with  XGrabServer():
https://github.com/sinev-valentine/passentry
Grabber:
https://www.thregr.org/~wavexx/software/screenkey
Аfter starting XGrabServer window "Promt for password", stdout and  window of grabber isn't refreshing. 
But after program is terminated, stdout and grabber window prints password.

Structure XSetWindowAttributes have field override_redirect.
If it set to true, indicates that a window should not be managed by window managers.
Setting this to true has no effect (after that, the window did not displayed).

**Comment by sinev-valentine** [comment]
Ways to solve the problem:
1)  working without compositor и non-reparenting window manager. 

2) starting secondary x-server

3) disable abilyty Xorg processing keypress. This can be done through synthesis of the events of disabling the device via a uevent . Then, run the unbind operation on the evdev and atkbd drivers. Then call bind (but with a different set of udev rules that prevent the user from opening the device).
The program "Prompt for password" can open the device /dev/input/event*
(either all at once, or by selecting the desired device from /proc/bus/input/devices) and read from there structure input_event.

4 )More "hacking" but an easy way to prevent Xorg from being able to read the keyboard:
- connect to the process using ptrace, 
- allocate an executable memory page, 
- - put there code that performs " close;open(/dev/null); dup2;int 3",
- move $pc to this page, 
- stop at int3, 
- free page 
- give the $ pc back.

**Comment by sinev-valentine** [comment]
Problem solution:

- call XIChangeProperty to set property "Device Enabled" to 0
- call ioctl(fevdev, EVIOCGRAB, 1)
- read password from evdev
- call XIChangeProperty to set property "Device Enabled" to 1

Password consist of keyscans, that defined in file /usr/include/linux/input-event-codes.h
To convert keysym into unicode format it is necessary:
 keyscans -> keycode(Xorg) -> keysym(Xorg) -> unicode
For this:
- keyscans + 8 (see str. 280 in evdev.c:  https://cgit.freedesktop.org/xorg/driver/xf86-input-evdev/tree/src/evdev.c)
- use XkbGetState() to define keyboard layout 
  use XkbKeycodeToKeysym() for convert  keycode(Xorg) to keysym(Xorg).
- use keysym2ucs() to convert  keysym(Xorg) to unicode.

**Comment by sinev-valentine** [comment]
All items completed except:
- reading keyboard  symbols , that require press more one key for input. (For example, French layout).
- interface between GUI and terminal program.
- integration into array-io-keychain

**Comment by sinev-valentine** [comment]
depended task #10 is  need to implement in future
