### ISSUE TITLE
Store other than json files in the key_data folder

### ISSUE THREAD

**Issue by dtaipov** [arrayio/array-io-keychain#84]
I've put a .gitignore file into the key_data folder. Because of that, could not create a key from command line:
```
>keychain.exe
{"command":"create","params":{"keyname":"sdfsdf","encrypted":true,"curve":"secp2
56k1","cipher":"aes256"}}
{"id":0,"error":"Error: cannot read keyfile"}
{"id":0,"error":"Error: cannot read keyfile"}
```
List command gives the same output
```
{"command": "list"}
{"id":0,"error":"Error: cannot read keyfile"}
{"id":0,"error":"Error: cannot read keyfile"}
```
Is it possible to store some other that *.json files in the key_data folder? If it's not, it would be useful, the error to say the exact problem like "Check if key_data folder contains only *.json files".

**Comment by roman-modelist-dev** [comment]
fixed
