### ISSUE TITLE
The signing of the transaction from the web (not from client)

### ISSUE THREAD

**Issue by sinev-valentine** [arrayio/array-io-keychain#9]
It is necessary  to implement a call to keychain from web site (swap.online, for example) to sign the transaction.  The Keychain must return the signed transaction to site. The POST method is supposed to be used.
The keychain must have command-line interface: https://github.com/arrayio/array-io-keychain/issues/15

**Comment by sinev-valentine** [comment]
For sending reply message curl may be used.
 keychain->fork()->exec(curl)
Passing message from keychain to curl - via SocketPair().

**Comment by sinev-valentine** [comment]
Another way to solve the problem:

Create program "WS-polling", for exchange between keychain and web site across websocket.
Scheme: 

![scheme](https://user-images.githubusercontent.com/37595780/41509323-baebb6f0-725a-11e8-81f5-2d152b639da3.png)

**Comment by sinev-valentine** [comment]
What is current status of this task at this moment?

**Comment by enaredzic** [comment]
Is this particular issue solved?

**Comment by roman-modelist-dev** [comment]
this issue is not actual at this moment
