### ISSUE TITLE
porting the gui-interface from sec_mod_windows to sec_mod_linux 

### ISSUE THREAD

**Issue by sinev-valentine** [arrayio/array-io-keychain#95]
For sec_mod_windows was developed interface passphrase entry. Development tool - QT. It is need to porting this interface to sec_mod_linux. Native tools for secure passphrase entry  must be cutted.

**Comment by roman-modelist-dev** [comment]
- need to add keychain logo
- need to add green/red lock and warning messages
- ethereum and bitcoin transactions is can not be parsed on linux

**Comment by sinev-valentine** [comment]
via Hubstaff
User: Sinev Valentine

Project: Array.IO keychain - https://app.hubstaff.com/projects/471254
Date Range: 01/15/19 - 02/21/19
Work session total: 88:27:38

Grand total: 88:27:38
